name: 'Terraform CI/CD'

# Run on pushes to the main branch and on any pull request
on:
  push:
    branches:
      - 'main'
  pull_request:

# Permissions needed for OIDC authentication
permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: 'ubuntu-latest'
    
    steps:
     
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Debug Repository Name'
        run: |
          echo "The job is running in repository: ${{ github.repository }}"
      
      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/53494160780/locations/global/workloadIdentityPools/vladan-ga-pool/providers/vladan-ga-provider'
          service_account: 'vladan-iac-terraform-deployer@sara-sandbox-interns.iam.gserviceaccount.com'

      - name: 'Setup Terraform'
        uses: 'hashicorp/setup-terraform@v3'

      - name: 'Terraform Init'
        run: 'terraform init'

      - name: 'Terraform Plan'
        run: 'terraform plan -no-color'
        if: github.event_name == 'pull_request'

      - name: 'Terraform Apply'
        run: 'terraform apply -auto-approve -no-color'
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'

      - name: 'Trigger Backend Cloud Build Pipeline'
        if: success() 
        run: |-
          echo "Terraform apply successful. Triggering the backend deployment."
          gcloud builds triggers run f1d484d9-ddb8-4e90-8be5-30994f48eaeb --branch=main

      - name: 'Trigger Frontend Cloud Build Pipeline'
        if: success()
        run: |-
          echo "Triggering the frontend deployment."
          gcloud builds triggers run 56c515db-1787-4557-93bc-d2b250a57d41 --branch=main